version: '3.1'

services:
  api:
    build: .
    container_name: radio-rolnik_api
    image: radio-rolnik/api
    restart: always
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis

    environment:
      HTTP_PORT: 3010
      WS_PORT: 3020

      DB_HOST: mongo
      DB_NAME: api
      DB_USER: radio-rolnikcred
      DB_PASS: radio-rolnikcred

      CACHE_HOST: redis
    ports:
      - 3010:3010
      - 3020:3020
    
  mongo:
    image: mongo:4.4
    container_name: radio-rolnik_mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    command: 
      - '--logpath'
      - '/var/log/mongodb/mongod.log'
      
    environment:
      MONGO_INITDB_ROOT_USERNAME: radio-rolnikcred
      MONGO_INITDB_ROOT_PASSWORD: radio-rolnikcred

  redis:
    image: redis:6.2-alpine
    container_name: radio-rolnik_redis
    restart: always

    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
