version: '3.1'

services:
  api:
    build: .
    restart: always
    environment:
      portHttp: 3010
      dbHost: db
      dbPort: 27017
      dbName: radio-rolnik
      dbAuth: admin
      dbUser: root
      dbPass: supersecurepassword123
      portWs: 3020
      CACHE_HOST: cache
      CACHE_PORT: 6379
    ports:
      - 3010:3010
      - 3020:3020
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:4.4
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecurepassword123
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
  cache:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 6379:6379
