version: '3.1'

services:
  api:
    image: radio-rolnik-api
    # build: .
    restart: always
    environment:
      portHttp: 3010
      dbHost: mongo
      dbPort: 27017
      dbName: radio-rolnik
      dbAuth: admin
      dbUser: root
      dbPass: supersecurepassword123
      portWs: 3020
    ports:
      - 3010:3010
      - 3020:3020
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersecurepassword123
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
